[project]
name = "pinochle"
version = "0.1.0"
description = "A distributed multi-player Pinochle game."
authors = [
    "Paul Kronenwetter <kronenpj@gmail.com>"
]
license = "GPL3"
readme = "README.md"
python = "^3.6"

[tool.poetry]
name = "pinochle"
version = "0.1.0"
description = "Multi-player, server-based Pinochle game."
authors = ["Paul Kronenwetter <kronenpj@gmail.com>"]
license = "GPL-2.0-only"
exclude = [ "*.db" ]

[tool.poetry.dependencies]
python = "^3.6"
jsonpickle = "^2.0.0"
brython="^3.9"
connexion = {version = "2.2.0", extras = ["swagger-ui"]}
openapi-spec-validator="0.2.9"
Flask="1.0.2"
flask-marshmallow="0.9.0"
Flask-SQLAlchemy="2.3.2"
gunicorn="^20.0.4"
# marshmallow="^2.18.0"
# marshmallow-sqlalchemy="^0.15.0"
# Version 3.x of marshmallow makes incompatible changes.
# I'm not ready to deal with the updates yet.
marshmallow="^2.21.0"
# marshmallow-sqlalchemy 0.24.x requires marshmallow 3.x
marshmallow-sqlalchemy="^0.23.1"
psycopg2-binary="^2.8.6"
SQLAlchemy="^1.2.17"
Werkzeug="^0.14.1"
#eralchemy
python-dateutil = "^2.8.1"
uuid = "^1.30"

[tool.poetry.dev-dependencies]
mockbrython = "^0.0.3"
pylint = "^2.7.2"
tox = "^3.23.0"
black = "^19.10b0"
pytest-cov = "^2.11.1"
rope = "^0.18.0"
#mutmut = "^2.1.0"
typing = [
    {version = "^3.7", python = "<=3.8.99"},
    {version = "< 3.7", python = "^3.9"},
]
pytest = "^6.2.2"
bumpversion = "^0.6.0"

[build-system]
requires = ["poetry_core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.black]
line-length = 88
target-version = ['py38']
include = '\.pyi?$'
exclude = '''

(
  /(
      \.eggs         # exclude a few common directories in the
    | \.git          # root of the project
    | \.hg
    | \.mypy_cache
    | \.tox
    | \.venv
    | _build
    | buck-out
    | build
    | dist
  )/
  | foo.py           # also separately exclude a file named foo.py in
                     # the root of the project
)
'''
